### ISSUE TITLE
Failure to join tables with encrypted data

### ISSUE THREAD

**Issue by ggershinsky** [ucbrise/opaque#28] opened 2018-03-13 14:12 UTC
I'll send the data samples used in this experiment.

1. val pers = spark.read.json("/path/json-person-rest_assured_payd_out.json"")
    val idlist = spark.read.json("/path/idlist.json")

2. val pe = pers.encrypted
    val ie = idlist.encrypted

3. pe.write.format("edu.berkeley.cs.rise.opaque.EncryptedSource").save("/path/encr_pers")
    ie.write.format("edu.berkeley.cs.rise.opaque.EncryptedSource").save("/path/encr_idlist")

4. val pp = spark.read.format("edu.berkeley.cs.rise.opaque.EncryptedSource")
         .schema(pers.schema).load("/path/encr_pers")

    val ii = spark.read.format("edu.berkeley.cs.rise.opaque.EncryptedSource")
         .schema(idlist.schema).load("/path/encr_idlist")

5. //Works
idlist.join(pers, pers("PersonID") === idlist("PersonId")).show

6.  // Process crash
ie.join(pe, pe("PersonID") === ie("PersonId")).show

"N3edu8berkeley2cs4rise6opaque4tuix8LessThanE can't operate on values of different types (StringField and LongField)"

7. // Fails with exception
ii.join(pp, pp("PersonID") === ii("PersonId")).show

"
18/03/13 15:46:48 WARN BlockManager: Putting block rdd_74_1 failed due to an exception
18/03/13 15:46:48 WARN BlockManager: Block rdd_74_1 could not be removed as it was not found on disk or in memory
18/03/13 15:46:48 ERROR Executor: Exception in task 1.0 in stage 45.0 (TID 101)
scala.MatchError: (Stream(),Stream()) (of class scala.Tuple2)
        at edu.berkeley.cs.rise.opaque.execution.ObliviousUnionExec$$anonfun$11.apply(operators.scala:340)
....
"

**Comment by ankurdave** [comment] 2018-03-21 00:32
2ff42e86f0641e1694cc68aacf2f611a44e63f6d should fix the crash in step 6. I haven't tried it on your particular input data yet, but the problem also occurs with TPC-H query 9.

**Comment by ggershinsky** [comment] 2018-03-21 13:42
Thanks, this indeed fixes the step 6 crash.
Step 7 exception still pops up.

**Comment by ankurdave** [comment] 2018-05-10 23:46
I couldn't reproduce this in `build/sbt console`, which uses Spark 2.0.2. Is it possible you're running a different Spark version?

**Comment by ggershinsky** [comment] 2018-05-11 06:02
We're working with Spark 2.0.1, but I've tried this with Spark 2.0.2, and got the same exception (step 7 above. Step 6 is fine now). I'm using Spark shell,
./bin/spark-shell  --jars ${OPAQUE_HOME}/target/scala-2.11/opaque_2.11-0.1.jar
import edu.berkeley.cs.rise.opaque.implicits._
edu.berkeley.cs.rise.opaque.Utils.initSQLContext(spark.sqlContext)
import org.apache.spark.sql.types._
val pers = spark.read.json("/home/gidon/Opaque/issue28/json-person-rest_assured_payd_out.json")
val idlist = spark.read.json("/home/gidon/Opaque/issue28/idlist.json")
val pe = pers.encrypted
val ie = idlist.encrypted
pe.write.format("edu.berkeley.cs.rise.opaque.EncryptedSource").save("/home/gidon/Opaque/issue28/encr_pers")
ie.write.format("edu.berkeley.cs.rise.opaque.EncryptedSource").save("/home/gidon/Opaque/issue28/encr_idlist")
val pp = spark.read.format("edu.berkeley.cs.rise.opaque.EncryptedSource").schema(pers.schema).load("/home/gidon/Opaque/issue28/encr_pers")
val ii = spark.read.format("edu.berkeley.cs.rise.opaque.EncryptedSource").schema(idlist.schema).load("/home/gidon/Opaque/issue28/encr_idlist")
// Fails with exception
ii.join(pp, pp("PersonID") === ii("PersonId")).show


I've also tried the Opaque "build/sbt console" - it got stuck following the  .encrypted operations, after printing these messages:

scala> val pe = pers.encrypted
pe: org.apache.spark.sql.DataFrame = [DateOfBirth: string, EmailAddress: string ... 6 more fields]

scala> val ie = idlist.encrypted
ie: org.apache.spark.sql.DataFrame = [PersonId: bigint]

scala> 18/05/11 07:47:53 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 9.148.26.173:42359 in memory (size: 14.9 KB, free: 639.3 MB)
18/05/11 07:47:53 INFO BlockManagerInfo: Removed broadcast_1_piece0 on 9.148.26.173:42359 in memory (size: 3.2 KB, free: 639.3 MB)
18/05/11 07:47:53 INFO BlockManagerInfo: Removed broadcast_2_piece0 on 9.148.26.173:42359 in memory (size: 14.8 KB, free: 639.3 MB)
18/05/11 07:47:53 INFO BlockManagerInfo: Removed broadcast_3_piece0 on 9.148.26.173:42359 in memory (size: 3.2 KB, free: 639.3 MB)

**Comment by ankurdave** [comment] 2018-05-11 06:41
That's helpful. I'll try again in the Spark shell, which might have some different configuration.

FYI, and apologies for the silly suggestion if this is not the case: the `build/sbt console` may not actually be stuck - try pressing enter and see if the `scala>` prompt gets printed again. Those INFO messages sometimes get printed on top of the prompt even when everything is working fine.

**Comment by ggershinsky** [comment] 2018-05-11 09:28
Thanks for the suggestion! I ran the console again, and this time the prompt appeared immediately after  each command. Moreover, the step 7 join was ok! So indeed it must be a Spark shell thing.

**Comment by ankurdave** [comment] 2018-05-27 21:46
Sorry for the delay on this. It should be fixed now.

**Closed** 2018-05-27 21:46 UTC

**Comment by ggershinsky** [comment] 2018-05-29 15:47
Thanks Ankur!
